M48
; DRILL file KiCad 10.0.1-10.0.1~ubuntu24.04.1 date 2026-05-08T08:47:15
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-08T08:47:15+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1-10.0.1~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X93.4Y-70.11
X93.4Y-75.89
T2
X97.7Y-59.2
X97.7Y-66.0
M30
